### ISSUE TITLE
ModalWindow with GWT MVP bug

### ISSUE THREAD

**Issue by yurii-polishchuk** [gwtbootstrap3/gwtbootstrap3#116]
Hello!
First of all, thanks for the great product, you're doing here a huge and good work ! =)

Me and my team are developing little education project with `gwt`. And to make it prettier, we tried `gwtbootstrap3`. Few words about: `GWT (MVP + UIBinder + AppController for history)`.

In one page we are using `ModalWindow`. With `GWT (DialogBox modal)` everything is ok. But when we refactored it with `<b:Modal...` http://gwtbootstrap3.github.io/gwtbootstrap3-demo/#modals exception popuped ;)

Test showed, that this exception is only with history "tokens". When view/presenter called not from history token, everything is ok with modal window.

Sample , it's just a pice of code, it can contains syntax mistakes, i just post it to show main purpose:
Presenter

``` java
public interface ResumePresenter {
    public void go(final HasWidgets container);
}
```

AppController

``` java
public class ResumeAppController implements ResumePresenter, ValueChangeHandler<String> {
    private final HandlerManager eventBus;
    private final ResumeServiceAsync rpcService;
    private HasWidgets container;
}

    private void bind() {
        History.addValueChangeHandler(this);

        eventBus.addHandler(AddResumeEvent.TYPE,
                new AddResumeEventHandler() {
                    public void onAddResume(AddResumeEvent event) {
                        doAddResume();
                    }
                });

    private void doAddResume() {
        History.newItem("resume");
        new AddResumePresenter(rpcService, eventBus, new AddResumeView()).go(container);
    }
}

    public void go(final HasWidgets container) {
        this.container = container;

        if ("".equals(History.getToken())) {
            History.newItem("show");
        } else {
            History.fireCurrentHistoryState();
        }
    }

   public void onValueChange(ValueChangeEvent<String> event) {
        String token = event.getValue();

        if (token != null) {
            ResumePresenter presenter = null;

            if (token.equals("show")) {
                presenter = new ShowResumePresenter(rpcService, eventBus, new ShowResumeView());
            }
            if (token.equals("resume")) {
                presenter = new AddResumePresenter(rpcService, eventBus, new AddResumeView());
            }
            if (presenter != null) {
                presenter.go(container);
            }
        }
```

Also there is Events, View, UIBinder, and Presenter files.

UIBinder file contain exaple from demo, and linked wit AddResumeView

``` xml
<b:Modal title="Cupcake ipsum" closable="true" fade="true" dataBackdrop="STATIC" dataKeyboard="true" b:id="myModal">
  <b:ModalBody>
    <g:HTML>Modal body...</g:HTML>
  </b:ModalBody>
  <b:ModalFooter>
    <b:Button type="PRIMARY">Do something</b:Button>
    <b:Button type="DANGER" dataDismiss="MODAL">Close</b:Button>
  </b:ModalFooter>
</b:Modal>

<b:Button dataTarget="#myModal" dataToggle="MODAL" type="PRIMARY" size="LARGE">Click to show modal</b:Button>
```

If we load it from event , onAddResume - everything is okey. But from token in onValueChange - exception appears.

```
onModuleLoad() threw an exception
Exception while loading module com......Resume. See Development Mode for details.

java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.google.gwt.dev.shell.ModuleSpace.onLoad(ModuleSpace.java:406)
    at com.google.gwt.dev.shell.OophmSessionHandler.loadModule(OophmSessionHandler.java:200)
    at com.google.gwt.dev.shell.BrowserChannelServer.processConnection(BrowserChannelServer.java:526)
    at com.google.gwt.dev.shell.BrowserChannelServer.run(BrowserChannelServer.java:364)
    at java.lang.Thread.run(Thread.java:744)
Caused by: com.google.gwt.event.shared.UmbrellaException: Exception caught: Exception caught: (TypeError) @org.gwtbootstrap3.client.ui.Modal::bindJavaScriptEvents(Lcom/google/gwt/dom/client/Element;)([JavaScript object(92)]): Object [object global] has no method 'jQuery'
    at com.google.gwt.event.shared.HandlerManager.fireEvent(HandlerManager.java:129)
    at com.google.gwt.user.client.impl.HistoryImpl.fireEvent(HistoryImpl.java:80)
    at com.google.gwt.event.logical.shared.ValueChangeEvent.fire(ValueChangeEvent.java:43)
    at com.google.gwt.user.client.impl.HistoryImpl.fireHistoryChangedImpl(HistoryImpl.java:87)
    at com.google.gwt.user.client.History.fireCurrentHistoryState(History.java:131)
    at com.......client.resume.ResumeAppController.go(ResumeAppController.java:80)
    at com.......client.resume.Resume.onModuleLoad(Resume.java:15)
    ... 9 more
Caused by: com.google.gwt.user.client.ui.AttachDetachException: Exception caught: (TypeError) @org.gwtbootstrap3.client.ui.Modal::bindJavaScriptEvents(Lcom/google/gwt/dom/client/Element;)([JavaScript object(92)]): Object [object global] has no method 'jQuery'
    at com.google.gwt.user.client.ui.AttachDetachException.tryCommand(AttachDetachException.java:87)
    at com.google.gwt.user.client.ui.Panel.doAttachChildren(Panel.java:170)
    at com.google.gwt.user.client.ui.Widget.onAttach(Widget.java:345)
    at com.google.gwt.user.client.ui.Composite.onAttach(Composite.java:162)
    at com.google.gwt.user.client.ui.Widget.setParent(Widget.java:475)
    at com.google.gwt.user.client.ui.Panel.adopt(Panel.java:127)
    at com.google.gwt.user.client.ui.ComplexPanel.add(ComplexPanel.java:97)
    at com.google.gwt.user.client.ui.AbsolutePanel.add(AbsolutePanel.java:97)
    at com.......client.resume.presenter.TestServiceByPanserPresenter.go(TestServiceByPanserPresenter.java:18)
    at com.......client.resume.ResumeAppController.onValueChange(ResumeAppController.java:109)
    at com.google.gwt.event.logical.shared.ValueChangeEvent.dispatch(ValueChangeEvent.java:128)
    at com.google.gwt.event.logical.shared.ValueChangeEvent.dispatch(ValueChangeEvent.java:1)
    at com.google.gwt.event.shared.GwtEvent.dispatch(GwtEvent.java:1)
    at com.google.web.bindery.event.shared.EventBus.dispatchEvent(EventBus.java:40)
    at com.google.web.bindery.event.shared.SimpleEventBus.doFire(SimpleEventBus.java:193)
    at com.google.web.bindery.event.shared.SimpleEventBus.fireEvent(SimpleEventBus.java:88)
    at com.google.gwt.event.shared.HandlerManager.fireEvent(HandlerManager.java:127)
    ... 15 more
Caused by: com.google.gwt.core.client.JavaScriptException: (TypeError) @org.gwtbootstrap3.client.ui.Modal::bindJavaScriptEvents(Lcom/google/gwt/dom/client/Element;)([JavaScript object(92)]): Object [object global] has no method 'jQuery'
    at com.google.gwt.dev.shell.BrowserChannelServer.invokeJavascript(BrowserChannelServer.java:249)
    at com.google.gwt.dev.shell.ModuleSpaceOOPHM.doInvoke(ModuleSpaceOOPHM.java:136)
    at com.google.gwt.dev.shell.ModuleSpace.invokeNative(ModuleSpace.java:571)
    at com.google.gwt.dev.shell.ModuleSpace.invokeNativeVoid(ModuleSpace.java:299)
    at com.google.gwt.dev.shell.JavaScriptHost.invokeNativeVoid(JavaScriptHost.java:107)
    at org.gwtbootstrap3.client.ui.Modal.bindJavaScriptEvents(Modal.java)
    at org.gwtbootstrap3.client.ui.Modal.onLoad(Modal.java:105)
    at com.google.gwt.user.client.ui.Widget.onAttach(Widget.java:350)
    at com.google.gwt.user.client.ui.AttachDetachException$1.execute(AttachDetachException.java:34)
    at com.google.gwt.user.client.ui.AttachDetachException.tryCommand(AttachDetachException.java:74)
    ... 31 more

```

**Comment by dyb22700** [comment]
Hi omatic-hacker,

I tried window top injection or ScriptInjector on bootstrap & jquery js to solved the fact that neither GWTTestCase nor GETTest (gwt-test-utils) fails on GWT 2.7 with same error on binding Javascript events for Model component, but it does not fix the issue with gwt-bootstrap3 !

GWT Test Utils
java.lang.UnsatisfiedLinkError: org.gwtbootstrap3.client.ui.Modal.bindJavaScriptEvents(Lcom/google/gwt/dom/client/Element;)V
	at org.gwtbootstrap3.client.ui.Modal.bindJavaScriptEvents(Native Method)
	at org.gwtbootstrap3.client.ui.Modal.onLoad(Modal.java:123)
	at com.google.gwt.user.client.ui.Widget.onAttach(Widget.java:359)
	at com.google.gwt.user.client.ui.Widget.setParent(Widget.java:484)
	at com.google.gwt.user.client.ui.Panel.adopt(Panel.java:124)
	at com.google.gwt.user.client.ui.ComplexPanel.add(ComplexPanel.java:105)
	at com.google.gwt.user.client.ui.AbsolutePanel.add(AbsolutePanel.java:98)
	at org.gwtbootstrap3.client.ui.Modal.checkIsAttached(Modal.java:296)
	at org.gwtbootstrap3.client.ui.Modal.show(Modal.java:223)...

GWTTestCase 
com.google.gwt.core.client.JavaScriptException: (null) @org.gwtbootstrap3.client.ui.Modal::bindJavaScriptEvents(Lcom/google/gwt/dom/client/Element;)([JavaScript object(19)]): null
	at com.google.gwt.dev.shell.BrowserChannelServer.invokeJavascript(BrowserChannelServer.java:252)
	at com.google.gwt.dev.shell.ModuleSpaceOOPHM.doInvoke(ModuleSpaceOOPHM.java:137)
	at com.google.gwt.dev.shell.ModuleSpace.invokeNative(ModuleSpace.java:589)
	at com.google.gwt.dev.shell.ModuleSpace.invokeNativeVoid(ModuleSpace.java:315)
	at com.google.gwt.dev.shell.JavaScriptHost.invokeNativeVoid(JavaScriptHost.java:107)
	at org.gwtbootstrap3.client.ui.Modal.bindJavaScriptEvents(Modal.java)
	at org.gwtbootstrap3.client.ui.Modal.onLoad(Modal.java:123)
	at com.google.gwt.user.client.ui.Widget.onAttach(Widget.java:359)
	at com.google.gwt.user.client.ui.Widget.setParent(Widget.java:484)
	at com.google.gwt.user.client.ui.Panel.adopt(Panel.java:124)
	at com.google.gwt.user.client.ui.ComplexPanel.add(ComplexPanel.java:105)
	at com.google.gwt.user.client.ui.AbsolutePanel.add(AbsolutePanel.java:98)
	at org.gwtbootstrap3.client.ui.Modal.checkIsAttached(Modal.java:296)
	at org.gwtbootstrap3.client.ui.Modal.show(Modal.java:223)
	at com.questel.usrmgmt.web.customer.client.core.widget.WaitingPopup.show(WaitingPopup.java:25)
	at com.questel.usrmgmt.web.customer.client.WaitingPopupTest.testWaitingPopup(WaitingPopupTest.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.gwt.junit.client.impl.GWTTestAccessor.invoke(GWTTestAccessor.java:39)
	at com.google.gwt.junit.client.impl.GWTRunner.executeTestMethod(GWTRunner.java:226)
	at com.google.gwt.junit.client.GWTTestCase.doRunTest(GWTTestCase.java:157)
	at junit.framework.TestCase.runTest(TestCase.java:59)
	at com.google.gwt.junit.client.GWTTestCase.runBare(GWTTestCase.java:151)
	at com.google.gwt.junit.client.GWTTestCase.__doRunTest(GWTTestCase.java:115)
	at com.google.gwt.junit.client.impl.GWTRunner.runTest(GWTRunner.java:302)
	at com.google.gwt.junit.client.impl.GWTRunner.doRunTest(GWTRunner.java:235)
	at com.google.gwt.junit.client.impl.GWTRunner.access$9(GWTRunner.java:229)
	at 

My test below (btw any advice on EasyMock with inherited module error in gwt.xml):

GWTTest
@Test
  public void testWaitingPopup() {
    WaitingPopup waitPopup = new WaitingPopup();

    waitPopup.show();

    assertThat(waitPopup.modal).isVisible();

    waitPopup.hide();

    assertThat(waitPopup.modal).isNotVisible();
  }

GWTTestCase
public void testWaitingPopup() {
    WaitingPopup waitPopup = new WaitingPopup();

    waitPopup.show();

    assertTrue(waitPopup.modal.isVisible());

    waitPopup.hide();

    assertTrue(!waitPopup.modal.isVisible());
  }
