### ISSUE TITLE
Select with GWT 2.8.0 does not work?

### ISSUE THREAD

**Issue by lofidewanto** [gwtbootstrap3/gwtbootstrap3#503]
Hi All,

I'm trying to use the Select component in my GWTBootstrap3 webapp with GWT 2.8.0. It does not show at all. Here is the result HTML: please see the attachment:

![2017-02-15 00_06_40-demo gwt webapp](https://cloud.githubusercontent.com/assets/1212950/22953724/b1625210-f312-11e6-97dd-fe4a3265c6c2.png)

Here is the code:

![2017-02-15 00_08_20-spring - demo-gwt-springboot_src_main_java_com_lofidewanto_demo_client_ui_person](https://cloud.githubusercontent.com/assets/1212950/22953793/f64e4a00-f312-11e6-911a-979c83929a28.png)

This is the exception:

`SEVERE: Exception caught: Exception caught: Exception caught: Exception caught: Exception caught: Exception caught: Exception caught: Exception caught: Exception caught: Exception caught: Exception caught: Exception caught: Exception caught: Exception caught: Exception caught: Exception caught: (TypeError) : ((intermediate value)(intermediate value) , $wnd).jQuery(...).selectpicker is not a function
com.google.gwt.user.client.ui.AttachDetachException: Exception caught: Exception caught: Exception caught: Exception caught: Exception caught: Exception caught: Exception caught: Exception caught: Exception caught: Exception caught: Exception caught: Exception caught: Exception caught: Exception caught: Exception caught: Exception caught: (TypeError) : ((intermediate value)(intermediate value) , $wnd).jQuery(...).selectpicker is not a function
	at Unknown.java_lang_Throwable_Throwable__Ljava_lang_String_2Ljava_lang_Throwable_2V(Throwable.java:74)
	at Unknown.java_lang_Exception_Exception__Ljava_lang_String_2Ljava_lang_Throwable_2V(Exception.java:33)
	at Unknown.java_lang_RuntimeException_RuntimeException__Ljava_lang_String_2Ljava_lang_Throwable_2V(RuntimeException.java:33)
	at Unknown.com_google_web_bindery_event_shared_UmbrellaException_UmbrellaException__Ljava_util_Set_2V(UmbrellaException.java:65)
	at Unknown.com_google_gwt_event_shared_UmbrellaException_UmbrellaException__Ljava_util_Set_2V(UmbrellaException.java:26)
	at Unknown.com_google_gwt_user_client_ui_AttachDetachException_AttachDetachException__Ljava_util_Set_2V(AttachDetachException.java:136)
	at Unknown.com_google_gwt_user_client_ui_AttachDetachException_tryCommand__Ljava_lang_Iterable_2Lcom_google_gwt_user_client_ui_AttachDetachException$Command_2V(AttachDetachException.java:87):
 `

**Comment by lofidewanto** [comment]
Hmm it could be the same problem as this one: https://github.com/gwtbootstrap3/gwtbootstrap3-extras/issues/223

But I don't see any double loading of JQuery...

**Comment by lofidewanto** [comment]
OK, workaround works also with GWT 2.8. So I close this point and we should follow this thread: gwtbootstrap3/gwtbootstrap3-extras#308
